/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kurskayit;

import static java.lang.Class.forName;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class Veritabaniİslemleri extends javax.swing.JFrame {

    
       static Connection baglanti;
      
       public static Connection baglantiAc(){            
             try {
                    forName("org.apache.derby.jdbc.EmbeddedDriver").newInstance();
                    
                    baglanti=DriverManager.getConnection("jdbc:derby://localhost:1527/kullanici","","");    
                    
             }
             catch (Exception e) {
             e.printStackTrace();
             }
             return baglanti;
       }
 
     
       public static void baglantiKapa(){           
             try { 
                    baglanti.close();
 
             } catch (SQLException e) {
                    e.printStackTrace();
             }                         
       }
 
      public void TabloDoldur() {
        try {

            Statement st = (Statement) baglantiAc();
            ResultSet res = st.executeQuery("SELECT * FROM  kurs");
            KursKayit model = new KursKayit(res);
            baglantiKapa(); 

        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, "Bağlantı Başarısız", "Veritabanı Bağlantısı", JOptionPane.PLAIN_MESSAGE);
    }
 }
      public void KayitEkle(String ad, String soyad, String tc, String tel) {
            try {
 
            Statement st = (Statement) baglantiAc();
            String sql= "INSERT INTO kurs VALUES (" +
            "'" + ad + "', " +
            "'" + soyad + "', " +
            "" + tc + ", " +
            "" + tel + ")";

         
            st.executeUpdate(sql); 

            baglantiKapa(); 

            TabloDoldur(); 

        }catch (Exception e) {
       
            JOptionPane.showConfirmDialog(null, "Kayıt Eklenemedi", "Kurs Tablosu", JOptionPane.PLAIN_MESSAGE);
        
        }
    }
      public void KayitSil(String tc) {
        try {
            Statement st = (Statement) baglantiAc();
            st.executeUpdate("Delete FROM  kurs where tc=" + tc);
            baglantiKapa(); 
            TabloDoldur(); 
        } catch (Exception e) {
        JOptionPane.showConfirmDialog(null, "Kayıt Silinemedi", "Kurs Tablosu", JOptionPane.PLAIN_MESSAGE);
    }
  }
      

    public Veritabaniİslemleri() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        isim = new javax.swing.JTextField();
        soyisim = new javax.swing.JTextField();
        tck = new javax.swing.JTextField();
        telno = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        tck1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ad");

        jLabel2.setText("Soyad");

        jLabel3.setText("TC Kimlik No");

        jLabel4.setText("Tel No");

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Öğrenci Ekle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        isim.setBackground(new java.awt.Color(204, 204, 204));

        soyisim.setBackground(new java.awt.Color(204, 204, 204));

        tck.setBackground(new java.awt.Color(204, 204, 204));
        tck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tckActionPerformed(evt);
            }
        });

        telno.setBackground(new java.awt.Color(204, 204, 204));

        jButton2.setBackground(new java.awt.Color(204, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Öğrenci Sil");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tck1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel5.setText("TC Kimlik No");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addGap(50, 50, 50)))
                                    .addGap(32, 32, 32))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(26, 26, 26)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(26, 26, 26)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tck1)
                            .addComponent(tck, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(isim, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(soyisim, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(telno, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)
                        .addGap(17, 17, 17)))
                .addContainerGap(112, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(isim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(soyisim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(telno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jButton1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tck1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jButton2)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //KAYIT EKLE
      
        PreparedStatement ps=null;
        Connection con=null;
        
        
        try{
            Class.forName("org.sqlite.JDBC");
            con=DriverManager.getConnection("jdbc:sqlite:C:\\Users\\Lenovo\\Documents\\NetBeansProjects\\kursKayit\\k.sqlite");
            ps=con.prepareStatement("INSERT INTO bilgi(ad,soyad,tc,tel) VALUES(?,?,?,?)");
            ps.setString(1, isim.getText());
            ps.setString(2, soyisim.getText());
            ps.setString(3, tck.getText());
             ps.setString(4, telno.getText());
                    ps.executeUpdate();
 } 
       catch(Exception ex){
           JOptionPane.showMessageDialog(null,"Öğrenci Veritabanı Sistemine Eklendi!");
        }finally{
        try
        {
        con.close();
        }
        catch(Exception ex)
                {
        }
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            try{
            ResultSet result;

        Connection con=null;
       String ara=String.valueOf( tck1.getText());
             Class.forName("org.sqlite.JDBC");
                con=DriverManager.getConnection("jdbc:sqlite:C:\\Users\\Lenovo\\Documents\\NetBeansProjects\\kursKayit\\k.sqlite");
       Statement st=con.createStatement();
        st.execute("DELETE FROM bilgi Where tc="+ara);

         
}
        catch (Exception e)
            
        {
            
            e.printStackTrace();
            JOptionPane.showMessageDialog(null,"Öğrenci Veritabanı Sisteminden Silindi!");

        }
        
      
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tckActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Veritabaniİslemleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Veritabaniİslemleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Veritabaniİslemleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Veritabaniİslemleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Veritabaniİslemleri().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField isim;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField soyisim;
    private javax.swing.JTextField tck;
    private javax.swing.JTextField tck1;
    private javax.swing.JTextField telno;
    // End of variables declaration//GEN-END:variables
}